services:
  appium-server:
    image: appium/appium:latest
    container_name: appium-server
    privileged: true
    ports:
      - "4773:4723"
    environment:
      - RELAXED_SECURITY=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: /bin/sh
    command: -c "appium driver install uiautomator2 || true && adb connect host.docker.internal:5555 && appium --relaxed-security"
    restart: unless-stopped

  viber-parser-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: viber-parser-api
    depends_on:
      - appium-server
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      APPIUM_SERVER_URL: "http://appium-server:4723"
      APPIUM_DEVICE_NAME: "LDPlayer"
      APPIUM_UDID: "host.docker.internal:5555"
      APPIUM_PLATFORM_VERSION: "9"
      APPIUM_APP_PACKAGE: "com.viber.voip"
      APPIUM_APP_ACTIVITY: "com.viber.voip.WelcomeActivity"
      APPIUM_NEW_COMMAND_TIMEOUT_SECONDS: "300"
      APPIUM_IMPLICIT_WAIT_SECONDS: "0"
      APPIUM_ADB_EXEC_TIMEOUT_SECONDS: "60"
      APPIUM_AUTO_CONNECT_ADB: "true"
      ADB_PATH: ""
      VIBER_DB_PATH: "/data/data/com.viber.voip/databases/viber_messages"
      VIBER_DB_QUERY_TIMEOUT_SECONDS: "60"
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}

    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped