services:
  android-emulator:
    image: shmayro/dockerify-android:latest
    container_name: android-emulator
    privileged: true
    devices:
      - /dev/kvm
      - /dev/net/tun
    ports:
      - "${EMULATOR_ADB_PORT}:5555"
      - "${EMULATOR_VNC_PORT}:6080"
      - "${EMULATOR_FRIDA_PORT}:27042"
    volumes:
      - viber-db:${VIBER_EMULATOR_DB_PATH}
      - android-data:/data
    environment:
      - EMULATOR_SYSTEM_IMAGE=${ANDROID_IMAGE}
      - ANDROID_PLATFORM_VERSION=${ANDROID_VERSION}
    restart: unless-stopped

  scrcpy-web:
    image: shmayro/scrcpy-web:latest
    container_name: scrcpy-web
    privileged: true
    ports:
      - "8000:8000"
    depends_on:
      android-emulator:
        condition: service_healthy
    command: >
      sh -c "adb connect android-emulator:5555 && npm start"
    restart: unless-stopped


  viber-parser-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: viber-parser-api
    depends_on:
      - android-emulator
    ports:
      - "${PORT}:8080"
    environment:
      PORT: "${PORT}"
      ADB_HOST: "${ADB_HOST}"
      ADB_PORT: "${ADB_PORT}"
      ADB_CONNECT_RETRIES: "${ADB_CONNECT_RETRIES}"
      FRIDA_HOST: "${FRIDA_HOST}"
      FRIDA_PORT: "${FRIDA_PORT}"
      VIBER_DB_PATH: "${VIBER_DB_PATH}"
      SUPABASE_URL: "${SUPABASE_URL:?SUPABASE_URL not configured}"
      SUPABASE_SERVICE_KEY: "${SUPABASE_SERVICE_KEY:?SUPABASE_SERVICE_KEY not configured}"
    volumes:
      - viber-db:${VIBER_API_DB_MOUNT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  viber-db:
  android-data: