ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.viber.plugins.RoutingKt.configureRouting
      - com.viber.plugins.MonitoringKt.configureMonitoring
      - com.viber.plugins.SerializationKt.configureSerialization
