[versions]
kotlin = "2.4.0"
logback = "1.5.37"
rabbitmq = "5.22.0"
ktor-openapi = "5.7.0"
slf4j = "2.0.13"
supabase = "3.8.0"
coroutines = "1.10.1"
koin = "4.0.4"

[libraries]
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
rabbitmq-client = { module = "com.rabbitmq:amqp-client", version.ref = "rabbitmq"}
ktor-openapi = { module = "io.github.smiley4:ktor-openapi", version.ref = "ktor-openapi"}
ktor-swagger-ui = { module = "io.github.smiley4:ktor-swagger-ui", version.ref = "ktor-openapi"}
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j"}
supabase-postgrest = { module = "io.github.jan-tennert.supabase:postgrest-kt", version.ref = "supabase"}
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "coroutines"}
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }